version: "3"

services:
  BE-template-master:
    image: "node:18-buster"
    environment:
      - node_env=development
      - port=3001
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    working_dir: "/app"
    entrypoint: "npm run"
    command: "start"
